name: Regression suite

on:
  push:
    branches:
      - Final-Branch
  pull_request:
    branches:
      - Final-Branch
  schedule:
    - cron: '30 2 * * *'

jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
      GOREST_TOKEN: ${{ secrets.GOREST_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Verify token exists
        run: |
         if [ -z "$GOREST_TOKEN" ]; then
         echo "::error ::GOREST_TOKEN is not set. Please add it in Repository Secrets."
         exit 1
         else
           echo "GOREST_TOKEN is set"
         fi


